import React from "react";
import { createRoot } from "react-dom/client";
import { App } from "./screens/App.jsx";
import "@fontsource/inter/latin-400.css";
import "@fontsource/inter/latin-500.css";
import "@fontsource/inter/latin-600.css";
import "@fontsource/inter/latin-700.css";
import "@fontsource/inter/latin-800.css";
import "./styles.css";
import "./reference-theme.css";
createRoot(document.getElementById("root")!).render(<App />);
